### ISSUE TITLE
How to train & test on a single channel grayscale images

### ISSUE THREAD

**Issue by ManuBN786** [MeijiTian/ZS-Denoisier-HREM#1]
Thank you for making your excellent work public !

The code works perfectly fine on the image included in the repo.

But my test cases are single channel grayscale images of size 256x256 similar to that of BioSR.

I tried to train it, it fails no matter how much I modify the code.

Any ideas would be appreciated.

**Comment by MeijiTian** [comment]
You may need to add an external channel to your train data manually. 
The shape of noisy data should be (1, 256, 256).

**Comment by ManuBN786** [comment]
Yes it works now !

But the results are not good. It is not denoising

I have attached a images in order : Noisy_Image---> ZS-Denoise_predicted---> Ground_Truth

I want denoised results to look like the GT

Training for more no. of epochs is not helping

![test_img](https://github.com/user-attachments/assets/5f0e1a42-4118-4bfe-b7c0-ba93624c8eb0)
Noisy Test Image

![_denoised_res_new](https://github.com/user-attachments/assets/0eb7934d-1013-4ea8-9b0a-aca78c8697d1)
ZS Denoised result

![gt_img](https://github.com/user-attachments/assets/35af5c70-b5ee-46d6-b409-c44be263e169)
GT

**Comment by MeijiTian** [comment]
I have seen your noisy and denoised results. The corrupted image is more like a blurring or defocused image, which may not be mainly corrupted by noise. The denoised result is reasonable since the proposed methods can not deal with the deblurring and defocussing problem in a self-supervised manner. I suggest you find some related work to deal with debluring and defocusing. And you may try some supervised methods. For self-supervised learning, you may need to incorporate the imaging forward model to improve the performance. Hope the suggestions would help.
